### ISSUE TITLE
仮想チャンネルを選択すると真っ白な画面になる

### ISSUE THREAD

**Issue by mikoto2000** [mikoto2000/scab-player#5]

**Comment by mikoto2000** [comment]
```
ChannelList.tsx:50 
 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ChannelList`. See https://reactjs.org/link/warning-keys for more information.
    at ChannelList (http://localhost:3000/static/js/bundle.js:435:63)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:56385:5)
    at Routes (http://localhost:3000/static/js/bundle.js:57119:5)
    at div
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:2725:50)
    at App (http://localhost:3000/static/js/bundle.js:55:88)
    at Router (http://localhost:3000/static/js/bundle.js:57053:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:54954:5)
ChannelList	@	ChannelList.tsx:50
history.ts:701 
 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at createURL (history.ts:701:1)
    at Object.encodeLocation (history.ts:729:1)
    at hooks.tsx:475:1
    at Array.map (<anonymous>)
    at useRoutesImpl (hooks.tsx:467:1)
    at useRoutes (hooks.tsx:344:1)
    at Routes (components.tsx:515:1)
    at renderWithHooks (react-dom.development.js:15486:1)
    at updateFunctionComponent (react-dom.development.js:19617:1)
    at beginWork (react-dom.development.js:21640:1)
history.ts:701 
 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at createURL (history.ts:701:1)
    at Object.encodeLocation (history.ts:729:1)
    at hooks.tsx:475:1
    at Array.map (<anonymous>)
    at useRoutesImpl (hooks.tsx:467:1)
    at useRoutes (hooks.tsx:344:1)
    at Routes (components.tsx:515:1)
    at renderWithHooks (react-dom.development.js:15486:1)
    at updateFunctionComponent (react-dom.development.js:19617:1)
    at beginWork (react-dom.development.js:21640:1)
react-dom.development.js:18704 
 The above error occurred in the <Routes> component:

    at Routes (http://localhost:3000/static/js/bundle.js:57119:5)
    at div
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:2725:50)
    at App (http://localhost:3000/static/js/bundle.js:55:88)
    at Router (http://localhost:3000/static/js/bundle.js:57053:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:54954:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
history.ts:701 
 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at createURL (history.ts:701:1)
    at Object.encodeLocation (history.ts:729:1)
    at hooks.tsx:475:1
    at Array.map (<anonymous>)
    at useRoutesImpl (hooks.tsx:467:1)
    at useRoutes (hooks.tsx:344:1)
    at Routes (components.tsx:515:1)
    at renderWithHooks (react-dom.development.js:15486:1)
    at updateFunctionComponent (react-dom.development.js:19617:1)
    at beginWork (react-dom.development.js:21640:1)
﻿


```

**Comment by mikoto2000** [comment]
9cc32c8bf2a3e555064a12cb48104656dabc8521 で修正。
